# Generated by Django 5.1.2 on 2024-10-26 14:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Perfil",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identificador único del perfil.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Correo electrónico único del usuario.",
                        max_length=254,
                        unique=True,
                    ),
                ),
                (
                    "fecha_registro",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Fecha y hora de registro del perfil.",
                    ),
                ),
                (
                    "nickname",
                    models.CharField(
                        blank=True, help_text="Apodo del usuario.", max_length=100
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True, help_text="Biografía del usuario.", max_length=500
                    ),
                ),
                (
                    "facebook",
                    models.CharField(
                        blank=True,
                        help_text="URL de Facebook del usuario.",
                        max_length=100,
                    ),
                ),
                (
                    "twitter",
                    models.CharField(
                        blank=True,
                        help_text="URL de Twitter del usuario.",
                        max_length=100,
                    ),
                ),
                (
                    "instagram",
                    models.CharField(
                        blank=True,
                        help_text="URL de Instagram del usuario.",
                        max_length=100,
                    ),
                ),
                (
                    "imagen",
                    models.ImageField(
                        default="perfiles/imagen_predeterminada/imagen_de_perfil_predeterminada.png",
                        help_text="Imagen de perfil del usuario.",
                        upload_to="perfiles/",
                    ),
                ),
                (
                    "premium",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si el usuario tiene una cuenta premium.",
                    ),
                ),
                (
                    "karma",
                    models.IntegerField(
                        default=0, help_text="Puntuación de karma del usuario."
                    ),
                ),
                (
                    "votos_positivos",
                    models.IntegerField(
                        default=0, help_text="Cantidad de votos positivos recibidos."
                    ),
                ),
                (
                    "votos_negativos",
                    models.IntegerField(
                        default=0, help_text="Cantidad de votos negativos recibidos."
                    ),
                ),
                (
                    "posts",
                    models.IntegerField(
                        default=0, help_text="Cantidad de publicaciones realizadas."
                    ),
                ),
                (
                    "comentarios",
                    models.IntegerField(
                        default=0, help_text="Cantidad de comentarios realizados."
                    ),
                ),
                (
                    "guardados",
                    models.IntegerField(
                        default=0, help_text="Cantidad de elementos guardados."
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("activo", "Activo"),
                            ("inactivo", "Inactivo"),
                            ("bloqueado", "Bloqueado"),
                            ("suspendido", "Suspendido"),
                            ("en_revision", "En revisión"),
                            ("baneado", "Baneado"),
                            ("eliminado", "Eliminado"),
                        ],
                        default="activo",
                        help_text="Estado actual del perfil.",
                        max_length=100,
                    ),
                ),
                (
                    "verificado",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si el perfil ha sido verificado.",
                    ),
                ),
                (
                    "sitio_web",
                    models.URLField(
                        blank=True, help_text="Sitio web personal del usuario."
                    ),
                ),
                (
                    "localidad",
                    models.CharField(
                        blank=True, help_text="Localidad del usuario.", max_length=100
                    ),
                ),
                (
                    "pais",
                    models.CharField(
                        blank=True, help_text="País del usuario.", max_length=100
                    ),
                ),
                (
                    "fecha_nacimiento",
                    models.DateField(
                        blank=True,
                        help_text="Fecha de nacimiento del usuario.",
                        null=True,
                    ),
                ),
                (
                    "genero",
                    models.CharField(
                        blank=True,
                        choices=[("masculino", "Masculino"), ("femenino", "Femenino")],
                        help_text="Género del usuario.",
                        max_length=100,
                    ),
                ),
                (
                    "lista_negra",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Lista negra de usuarios.",
                        related_name="lista_negra_de",
                        to="usuarios.perfil",
                    ),
                ),
                (
                    "suscripciones",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Usuarios a los que está suscrito.",
                        related_name="suscriptores",
                        to="usuarios.perfil",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        help_text="Usuario asociado al perfil.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil",
                "verbose_name_plural": "Perfiles",
                "ordering": ["-fecha_registro"],
                "indexes": [
                    models.Index(
                        fields=["usuario"], name="usuarios_pe_usuario_74afa8_idx"
                    ),
                    models.Index(fields=["email"], name="usuarios_pe_email_68060f_idx"),
                    models.Index(
                        fields=["nickname"], name="usuarios_pe_nicknam_f1e0a6_idx"
                    ),
                    models.Index(
                        fields=["estado"], name="usuarios_pe_estado_dcf737_idx"
                    ),
                ],
            },
        ),
    ]
