# Generated by Django 5.1.2 on 2024-10-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perfil",
            name="imagen",
            field=models.ImageField(
                default="usuarios/img/perfil/default/imagen_de_perfil_predeterminada.png",
                help_text="Imagen de perfil del usuario.",
                upload_to="usuarios/img/perfil/",
            ),
        ),
    ]
